name: 🤖 Auto move new issues into triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/routelink/projects/1
          github-token: ${{ secrets.ROUTELINKBOT_TOKEN }}
